#!/bin/bash

APP_DIR=code
APP_DIR_CONF=code_conf

FILE=$APP_DIR*.zip

if test -f $FILE; then
	
	echo   Starting update process
	echo   .  Application directory: $APP_DIR
	echo   .  Configuration directory: $APP_DIR_CONF

	echo   .  Unzipping archive
	unzip -qq *.zip
	rm *.zip

	echo   .  Stopping application
	kill $(cat /var/www/$APP_DIR/RUNNING_PID)

	echo   .  Removing previous version from production directory
	rm -r /var/www/$APP_DIR/*

	echo   .  Copying new version into production directory
	cp -r $APP_DIR*/* /var/www/$APP_DIR

	echo   .  Removing staging directory
	rm -r $APP_DIR*

	echo   .  Starting application
	/var/www/$APP_DIR/bin/$APP_DIR -Dconfig.file=/var/www/$APP_DIR_CONF/production.conf -Dlogger.file=/var/www/$APP_DIR_CONF/logback.xml &

	sleep 5
	echo   .  Removing log artifact
	rm -r logs

	echo Done!

else 
	echo Update file $FILE not found. Please upload ZIP archive.

fi
